### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
* Old style exceptions --> new style for Python 3
    * Python 3 treats old style exceptions as syntax errors but new style exceptions work as expected in both Python 2 and Python 3.
* Use __print()__ function in both Python 2 and Python 3
    * __print()__ is a function in Python 3.

### CODE REVIEW

**Comment by cclauss** [comment]
@cybernet, @NotoriuosRebel, @DJCHICKEN4, @nqmetke Instead of a 👍 could I please ask you to __Review changes__ because that will give @jofpin more confidence that each of you has read through the actual changes and believes that those changes improve the state of the project?

_Anyone_ can review a GitHub pull request:
1. Scroll up on this page and click on __Files changed__ above.
2. Click on the green button __Review changes__
3. Click on __Comment__ or __Approve__ or __ Request changes__

Thanks for taking the time to go through these step which help maintainers.

**Comment by DJCHICKEN4** [comment]
@cclauss I will do that I was previously unaware that anyone could review the code.

**Comment by cclauss** [comment]
Try this on the command line: __python2 -c “from __future__ import print_function ; print ‘Hi’”

This the future import _prevents_ Python 2 developers from adding legacy print statements that will break Python 3 compatibility.  On Python 2 the import is also _required_ for any print statement that redirects to a file or uses a comma or a parameter like __end=__, __file__, etc.

**Comment by NotoriousRebel** [comment]
Ah, I see now thanks for the clear up, I didn't realize you could import from future in python3 as I was going to suggest wrapping it in a try-except statement to determine what version you're currently using to keep backward compatibility alive.

**Pull request closed without merging**
