### PR TITLE
add badge(s)

### PR DESCRIPTION
**Pull request by noraj**
Your tool/software has been inventoried on [*Rawsec's CyberSecurity Inventory*](https://inventory.rawsec.ml/).

### What is Rawsec's CyberSecurity Inventory?

An inventory of tools and resources about CyberSecurity. This inventory aims to help people to find everything related to CyberSecurity.

+ **Open source**: Every information is available and up to date. If an information is missing or deprecated, you are invited to (help us).
+ **Practical**: Content is categorized and table formatted, allowing to search, browse, sort and filter.
+ **Fast**: Using static and client side technologies resulting in fast browsing.
+ Rich tables: search, sort, browse, filter, clear
+ Fancy informational popups
+ Badges / Shields
+ Static API
+ Twitter bot

More details about features [here](https://inventory.rawsec.ml/features.html).

Note: the inventory is a FLOSS (Free, Libre and Open-Source Software) project.

### Why?

+ **Specialized websites**: Some websites are referencing tools but additional information is not available or browsable. Make additional searches take time.
+ **Curated lists**: Curated lists are not very exhaustive, up to date or browsable and are very topic related.
+ **Search engines**: Search engines sometimes does find nothing, some tools or resources are too unknown or non-referenced. These is where crowdsourcing is better than robots.

### Why should you care about being inventoried?

Mainly because this is giving visibility to your tool, more and more people are using the *Rawsec's CyberSecurity Inventory*, this helps them find what they need.

### Why the badge?

The badge shows to your community that your are inventoried. This also shows you care about your project and want it growing, that your tool is not an abandonware.

Also we took time to inventory your tool and you are gaining visibility from that: **we added your tool to our inventory to make it known now it is your turn to add the badge to your project README to help our project being known**.

### Ok but...

You should think I asked nothing to you, I don't need visibility or/and I don't like your badge: your are free not to use it.

### CODE REVIEW

**Comment by jofpin** [comment]
Good ideas, thank you very much. I just passed it.

**Comment by noraj** [comment]
@jofpin You're welcome, keep up the good work with rape ;)

**Comment by noraj** [comment]
PS : I don't know if it is deliberate but you undid it just after.

image

**Comment by 0xInfection** [comment]
How to do self-promotion like a boss. 

*slow claps*

**Comment by 0xInfection** [comment]
Self promotion via other's project where you have no contribution? Nice.

_*slow claps*_

**Comment by 0xInfection** [comment]
Self promotion via other's project where you have no contribution? Nice.  * slow claps *

**Comment by noraj** [comment]
@0xInfection 

> Also we took time to inventory your tool and you are gaining visibility from that: we added your tool to our inventory to make it known now it is your turn to add the badge to your project README to help our project being known.

I think your judgment is not fair. I'm spending tons of hours for this FLOSS project (https://gitlab.com/rawsec/rawsec-cybersecurity-list). I'm doing it nearly alone, contributions are extremely rare. I'm receiving zero money or any benefit for that. It is only to share knowledge to all cybersecurity enthusiast, for free! So helping the project to be known is helping that cause (share of knowledge for free) not self promoting me. I hope you'll understand that and change your mind.

**Comment by 0xInfection** [comment]
@noraj, First of all lets clear off your mind about the money part. When you decide to do work for a FLOSS project, you pre-hold the assumption that you will be doing it for free without any money. You're just holding up a single project which is simply a collection of tools. Think about me maintaining 2 projects coded without any personal/monetary profit. Past week, I open-sourced my years of hard work ([Awesome-WAF](https://github.com/0xinfection/Awesome-WAF)) for absolutely nothing. I get it that you are just maintaining a list of tools, thats it. But I guess yours is not the only unique one in this cysec-verse. Kitploit, ToolsWatch and many others too have similar stuff, I've never seen them approaching project maintainers to include a badge that their tool has been "inventoried". Is absurd trust me.

**Comment by 0xInfection** [comment]
@noraj, First of all lets clear off your mind about the money part. When you decide to do work for a FLOSS project, you pre-hold the assumption that you will be doing it for free without any money. You're just holding up a single project which is simply a collection of tools. Think about other open source contributors who maintain their projects without any personal/monetary profit. Past week, I open-sourced my years of hard work ([Awesome-WAF](https://github.com/0xinfection/Awesome-WAF)) for absolutely nothing. I get it that you are just maintaining a list of tools, but thats it. I guess yours is not the only unique one in this cysec-verse. Kitploit, ToolsWatch and many others too have similar stuff, I've never seen them approaching project maintainers to include a badge that their tool has been "inventoried". Your just trying to get recognition but its absurd trust me. If people likes your work, they'll give you recognition without any hesitation.

**Comment by noraj** [comment]
@0xInfection 

1) This is an inventory not a list like all the other or a news blog like Kitploit and ToolsWatchs. See the overview here:
image
and most importantly features here: https://inventory.rawsec.ml/features.html
A bare awesome list is a simple markdown file that get huge the more tool you add and that begins quite unmaintainable and unsearchable the bigger its become. That's the whole idea of getting this inventory.

2) I'm not trying to get recognition, I'm not branding my name or pseudo elsewhere than on the website footer. A lot of awesome list have *natural* huge coverage just because they are hosted on Github, because people are massively present on github, already have an account are already per-logged in, can easily star the project, etc. But this is a website (and its source are on gitlab) so the project is not getting as much visibility or contributions. Because the project is far from Social Networks (like GitHub is for dev and techs) the project needs an alternative way to be known.

3) Yeah badges this badge is totally stupid, it is only to get people curious and see what is the inventory, and know about it. (not getting me recognition in any way, that's not the goal, that's why the project is not hosted on a personal repository but in an organization).

4) a) Since the beginning of the project (between 1 or 2 years i don't remember), the project add nearly no contributions except one or two from people I personally know that were curious at the beginning. I assume this is totally due to the fact is it not as trivial as a text file on github. People are too lazy to make a contribution on gitlab and they fear it is complicated even if its not true.
b) I saw not podcast, blog article, or any way of branding about the project so I assume it is not very known. 
c) I never received a private message or even a comment on twitter to thanks me, giving an idea, giving a feedback, asking for a new tool to be invotoried, etc. so I guess that very few people heard about the project.
d) Like you I spent years and huge efforts into this project so I really don't want it to be gorgotten and unused. That's all. I'm not asking for fame in any way.

**Comment by 0xInfection** [comment]
1. Why don't you switch over to conventional methods so that it reaches people. As far as my experience with open source goes, people are really welcoming. When you want contributions, you should know that it should be conventional in every way? Past 2 years you have been working on this and guess what, you have not got recognition so far. Don't you sense something is wrong in your method?
2. > Because the project is far from Social Networks (like GitHub is for dev and techs) the project needs an alternative way to be known.

Evidence is contradictory to your point: https://github.com/noraj/rawsec-cybersecurity-inventory
Last commit: 1 hour ago.

**Comment by noraj** [comment]
> Why don't you switch over to conventional methods so that it reaches people. As far as my experience with open source goes, people are really welcoming. When you want contributions, you should know that it should be conventional in every way? Past 2 years you have been working on this and guess what, you have not got recognition so far. Don't you sense something is wrong in your method?

Because GitHub have some technical limitations that GitLab has not. And because a huge all in one markdown file has some heavy drawback that I talked about and make impossible several features, is unmaintainable, etc. The fact is OSS works with this rule **100/10/1**, from 100 people 10 will open an issue an only 1 will contribute. Low contribution is not specific to my project. And casual people will randomly contribute ONLY if it is DEAD simple (like a text list). Having to add a line in a JSON file instead is affraiying for them even if it is as simple in reality.

> Evidence is contradictory to your point: https://github.com/noraj/rawsec-cybersecurity-inventory

This is a mirror of the Gitlab repo if you read the description:

image

So if you meant it is on github, it is not, it is on gitlab here https://gitlab.com/rawsec/rawsec-cybersecurity-list

And if you meant it is under my pseudo and not an org, this is because this is the mirror, the true repository is under an org:
image

**Comment by noraj** [comment]
@0xInfection For the badge notification, 50% of people are welcoming me and merging the badge, 30% ignore it (because project is unmaintained), 10% ignore it because they are no interested and doesn't answer, and 10% (like you) are unyielding (i dont know if it is the good word).

**Comment by 0xInfection** [comment]
@noraj, wow I just tweeted about your work so that you get some recognition for your hard work and I come back to see this. 🙂

> You see where you're wrong. 🙂

**Comment by noraj** [comment]
@0xInfection That's kind from you. I guess I owe you one tweet.

**Comment by 0xInfection** [comment]
Nope, please don't. You should really not defame yourself by associating with an "unyielding" person.

**Comment by noraj** [comment]
@0xInfection 
I don't know why you were so aggressive in the first place:
image
when the project maintainer was happy about it: 
image
And now you are mocking me again.
image
Just feel happy that someone is working hard and is disinterested like you to share knowledge, instead of attack people you don't know.

**Comment by 0xInfection** [comment]
1. I've been an open-source contributor for past 2 years and the worst possible way of contribution I've seen is like either correcting words, or adding something lame to the README file which irks me. Make some code changes, yeah then thats a valid contribution.
2. Then I saw that you included your "badge" in the contributions, which irritated me further.
3. As far as I see it, the project author wasn't cool with it, so [he reverted it](https://github.com/jofpin/trape/pull/131#issuecomment-463748748).
4. I don't mock anyone, I re-stated how I had been mocked even after having the goodwill of spreading the word your work.
5. If you think I'm disinterested in sharing knowledge, then mate your damn lagging behind. I would not have open sourced my years of hard work if I did not have the intention of sharing knowledge. 🙂

**Comment by noraj** [comment]
> I've been an open-source contributor for past 2 years and the worst possible way of contribution I've seen is like either correcting words, or adding something lame to the README file which irks me. Make some code changes, yeah then thats a valid contribution.

I don't agree, spelling and typo in documentation or README also counts.

> Then I saw that you included your "badge" in the contributions, which irritated me further.

What are you talking about?

> I never mock anyone, I re-stated how [I had been mocked](https://github.com/jofpin/trape/pull/131#issuecomment-473575827) even after having the goodwill of spreading the word your work.

image

I didn't mock you after your tweet but thanked you... I don't understand what you mean.

> If you think I'm disinterested in sharing knowledge, then mate you're damn lagging behind. I would not have open sourced my years of hard work if I did not have the intention of sharing knowledge. slightly_smiling_face

I didn't say that. My sentence was a bit confusing. I meant you are disinterested (not to share) but to get recognition.

I should have wrote

>  Just feel happy that someone is disinterested and is working hard to share knowledge, like you are, instead of attack people you don't know.

Instead of 

> Just feel happy that someone is working hard and is disinterested like you to share knowledge, instead of attack people you don't know.

**Comment by noraj** [comment]
@0xInfection I think we talked too much about it. We have the same goal of sharing knowledge and participating to FLOOS projects. In the first place don't go on issue comments only to say to people that their Pull Request is useless or that they do it for fame or things like that.
That's not even your project here. Let the owner managing that.
And if you disagree be constructive instead of being salty.

**Pull request merged**
