### PR TITLE
Small bug fixes to make trape functional again

### PR DESCRIPTION
**Pull request by jerjet**
Hi, great tool thank you for writing it! We made some small changes for it to work again. I know it solved our problems and think it will address a few open issues on your repo. Feel free to edit as needed. Credit goes to https://github.com/tdenisenko for the bug fixes.

### CODE REVIEW

**Comment by tomasvieira** [comment]
tks!!...work in 22/05/2020

**Comment by pretech86** [comment]
after entered all tokens it requested it a again

**Comment by pretech86** [comment]
So trap working a gain or not ?

**Comment by pretech86** [comment]
it give me this error @jerjet  

[x] ERROR: cannot import name json

**Comment by carlocrasti** [comment]
I'm always "Waiting for the users to fall..."

**Comment by ziomik** [comment]
quote..

**Comment by SandorSzavost28** [comment]
Have you noticed Ngrok is "working"... and still showing "We can't connect with Ngrok" error message.

The Ngrok tunnel is actually working while Trape is running, but it is pointing to "http://127.0.0.1:2727", not to the real lure link which in my case would be something like "http://127.0.0.1:2727/examplepage.com". 

I say that Ngrok is "working" because the lure link is accesible throug the tunnel link adding the missing part /"examplepage.com" at the final of the Ngrok link, which you can see in your Ngrok Panel at "http://127.0.0.1:4040", So  "http://1f835abcdef73d.ngrok.io/examplepage.com" actually works with some help.

There is something missing when calling Ngrok, check the screenshots, Hope it helps!

Trape JPino NGrok Activo1

Trape JPino NGrok Activo2

**Comment by carlocrasti** [comment]
Hi Sandor, thanks for the reply, but my ngrok works perfectly, I have no errors. Both local and public information are correct. Unfortunately when I launch control panel link, access key and public lure I always remain in "Waiting for the users to fall" ..... there is no connection. If anyone has encountered such an error and has resolved it please let me know. I seem to have checked everything .... thanks anyway for the interest

**Comment by basheer69** [comment]
> Hi Sandor, thanks for the reply, but my ngrok works perfectly, I have no errors. Both local and public information are correct. Unfortunately when I launch control panel link, access key and public lure I always remain in "Waiting for the users to fall" ..... there is no connection. If anyone has encountered such an error and has resolved it please let me know. I seem to have checked everything .... thanks anyway for the interest

Has this still not been fixed...coz thats what am getting

**Pull request merged**
